### ISSUE TITLE
Need upload script for BC13 data

### ISSUE THREAD

**Issue by gicmo** [G-Node/GCA-Web#167]

**Comment by asobolev** [comment]
GUI
https://portal.g-node.org/abstracts/bc13/

Data
https://portal.g-node.org/abstracts/bc13/bc13data.js

**Comment by asobolev** [comment]
actual abstracts from bc14

JSON
http://abstracts.g-node.org/api/conferences/ba604a3c-e95a-4569-84a9-7d4dedd08310/abstracts

GUI
http://abstracts.g-node.org/conference/BC14/abstracts#/uuid/88312f4d-ccb4-4f1e-ab99-8a8776435662
