### ISSUE TITLE
Check for compatibility to https per default

### ISSUE THREAD

**Issue by gicmo** [G-Node/GCA-Web#172]
We should make sure that all links are transport relative, i.e. we return links with https: when they were requested with https and otherwise.

Found issues:

- [x] Google Font links
- [ ] Logo url in the conference settings (only mixed content warning)
- [ ] Thumbnail url in the conference settings (only mixed content warning)

**Comment by stoewer** [comment]
I just tested the current version with an apache2 as proxy and enforced ssl for the whole app (configuration below). In this mode all parts that I tested (hopefully everything) works fine.

Further I greped for potentially harmful code and found nothing critical.

Therefore I believe we can consider this issue as done.

Apache virtual host conf:
```
<VirtualHost *:80>
    ServerName ruby.cns.bzm
	<IfModule mod_rewrite.c>
           RewriteEngine On
           RewriteCond %{HTTPS} off
           RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
    </IfModule>
</VirtualHost>

<VirtualHost *:443>
    ServerName ruby.cns.bzm
    ProxyPreserveHost On
    ProxyRequests Off
    ProxyPass / http://localhost:9000/
    ProxyPassReverse / http://localhost:9000/
    ErrorLog /var/log/apache2/ruby.cns.bzm.log
    LogLevel warn
    SSLEngine On
    SSLCertificateFile	/etc/ssl/certs/ssl-cert-snakeoil.pem
    SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key
</VirtualHost>
```

**Comment by stoewer** [comment]
However, when creating a conference we have to keep in mind to have https urls to logo and banner images.
