### ISSUE TITLE
Find out if MySQL performs better

### ISSUE THREAD

**Issue by stoewer** [G-Node/GCA-Web#226]
Check if #216 is still an issue when using MySQL instead of Postgres.

**Comment by asobolev** [comment]
Comments to migration to MySQL:

1. JPA creates automatically non-m2m tables with upper-case names, while pg_dump will store everything as lower-case. InnoDB is case-sensitive
2. affiliation table has legacy "name" column in PROD, maybe should be removed later

**Comment by asobolev** [comment]
list all abstracts currently results in the following SQL:

150120 14:00:34	   55 Query	SELECT UUID, AUTHENTICATIONMETHOD, AVATAR, FIRSTNAME, FULLNAME, LASTNAME, MAIL, PROVIDER, USERID, SECRET, TOKEN, ACCESSTOKEN, EXPIRESIN, REFRESHTOKEN, TOKENTYPE, HASHER, PASSWORD, SALT FROM ACCOUNT WHERE ((LOWER(USERID) = LOWER('sobolev.andrey@gmail.com')) AND (PROVIDER = 'userpass'))

		   55 Query	SELECT DISTINCT t1.UUID, t1.CITE, t1.DEADLINE, t1.DESCRIPTION, t1.ENDDATE, t1.ISOPEN, t1.ISPUBLISHED, t1.LINK, t1.LOGO, t1.NAME, t1.SHORT, t1.STARTDATE, t1.THUMBNAIL, t0.UUID, t0.NAME, t0.PREFIX, t0.SHORT, t0.CONFERENCE_UUID, t2.UUID, t2.AUTHENTICATIONMETHOD, t2.AVATAR, t2.FIRSTNAME, t2.FULLNAME, t2.LASTNAME, t2.MAIL, t2.PROVIDER, t2.USERID, t2.SECRET, t2.TOKEN, t2.ACCESSTOKEN, t2.EXPIRESIN, t2.REFRESHTOKEN, t2.TOKENTYPE, t2.HASHER, t2.PASSWORD, t2.SALT, t3.UUID, t3.ACKNOWLEDGEMENTS, t3.CONFLICTOFINTEREST, t3.DOI, t3.ISTALK, t3.MTIME, t3.REASONFORTALK, t3.SORTID, t3.STATE, t3.TEXT, t3.TITLE, t3.TOPIC, t3.CONFERENCE_UUID, t4.UUID, t4.POSITION, t4.TOPIC, t4.CONFERENCE_UUID FROM CONFERENCE t1 LEFT OUTER JOIN ABSTRACTGROUP t0 ON (t0.CONFERENCE_UUID = t1.UUID) LEFT OUTER JOIN (conference_owners t5 JOIN ACCOUNT t2 ON (t2.UUID = t5.owners_UUID)) ON (t5.conferences_UUID = t1.UUID) LEFT OUTER JOIN ABSTRACT t3 ON (t3.CONFERENCE_UUID = t1.UUID) LEFT OUTER JOIN TOPIC t4 ON (t4.CONFERENCE_UUID = t1.UUID) WHERE ((t1.UUID = 'BC14') OR (t1.SHORT = 'BC14'))

150120 14:00:38	   55 Query	SELECT DISTINCT t1.UUID, t1.CITE, t1.DEADLINE, t1.DESCRIPTION, t1.ENDDATE, t1.ISOPEN, t1.ISPUBLISHED, t1.LINK, t1.LOGO, t1.NAME, t1.SHORT, t1.STARTDATE, t1.THUMBNAIL, t0.UUID, t0.NAME, t0.PREFIX, t0.SHORT, t0.CONFERENCE_UUID, t2.UUID, t2.AUTHENTICATIONMETHOD, t2.AVATAR, t2.FIRSTNAME, t2.FULLNAME, t2.LASTNAME, t2.MAIL, t2.PROVIDER, t2.USERID, t2.SECRET, t2.TOKEN, t2.ACCESSTOKEN, t2.EXPIRESIN, t2.REFRESHTOKEN, t2.TOKENTYPE, t2.HASHER, t2.PASSWORD, t2.SALT, t3.UUID, t3.ACKNOWLEDGEMENTS, t3.CONFLICTOFINTEREST, t3.DOI, t3.ISTALK, t3.MTIME, t3.REASONFORTALK, t3.SORTID, t3.STATE, t3.TEXT, t3.TITLE, t3.TOPIC, t3.CONFERENCE_UUID, t4.UUID, t4.POSITION, t4.TOPIC, t4.CONFERENCE_UUID FROM CONFERENCE t1 LEFT OUTER JOIN ABSTRACTGROUP t0 ON (t0.CONFERENCE_UUID = t1.UUID) LEFT OUTER JOIN (conference_owners t5 JOIN ACCOUNT t2 ON (t2.UUID = t5.owners_UUID)) ON (t5.conferences_UUID = t1.UUID) LEFT OUTER JOIN ABSTRACT t3 ON (t3.CONFERENCE_UUID = t1.UUID) LEFT OUTER JOIN TOPIC t4 ON (t4.CONFERENCE_UUID = t1.UUID) WHERE ((t1.UUID = 'ba604a3c-e95a-4569-84a9-7d4dedd08310') OR (t1.SHORT = 'ba604a3c-e95a-4569-84a9-7d4dedd08310'))

150120 14:00:41	   55 Query	SELECT UUID, AUTHENTICATIONMETHOD, AVATAR, FIRSTNAME, FULLNAME, LASTNAME, MAIL, PROVIDER, USERID, SECRET, TOKEN, ACCESSTOKEN, EXPIRESIN, REFRESHTOKEN, TOKENTYPE, HASHER, PASSWORD, SALT FROM ACCOUNT WHERE ((LOWER(USERID) = LOWER('sobolev.andrey@gmail.com')) AND (PROVIDER = 'userpass'))

150120 14:00:55 Query	SELECT DISTINCT t1.UUID, t1.CITE, t1.DEADLINE, t1.DESCRIPTION, t1.ENDDATE, t1.ISOPEN, t1.ISPUBLISHED, t1.LINK, t1.LOGO, t1.NAME, t1.SHORT, t1.STARTDATE, t1.THUMBNAIL, t0.UUID, t0.NAME, t0.PREFIX, t0.SHORT, t0.CONFERENCE_UUID, t2.UUID, t2.AUTHENTICATIONMETHOD, t2.AVATAR, t2.FIRSTNAME, t2.FULLNAME, t2.LASTNAME, t2.MAIL, t2.PROVIDER, t2.USERID, t2.SECRET, t2.TOKEN, t2.ACCESSTOKEN, t2.EXPIRESIN, t2.REFRESHTOKEN, t2.TOKENTYPE, t2.HASHER, t2.PASSWORD, t2.SALT, t3.UUID, t3.ACKNOWLEDGEMENTS, t3.CONFLICTOFINTEREST, t3.DOI, t3.ISTALK, t3.MTIME, t3.REASONFORTALK, t3.SORTID, t3.STATE, t3.TEXT, t3.TITLE, t3.TOPIC, t3.CONFERENCE_UUID, t4.UUID, t4.POSITION, t4.TOPIC, t4.CONFERENCE_UUID FROM CONFERENCE t1 LEFT OUTER JOIN ABSTRACTGROUP t0 ON (t0.CONFERENCE_UUID = t1.UUID) LEFT OUTER JOIN (conference_owners t5 JOIN ACCOUNT t2 ON (t2.UUID = t5.owners_UUID)) ON (t5.conferences_UUID = t1.UUID) LEFT OUTER JOIN ABSTRACT t3 ON (t3.CONFERENCE_UUID = t1.UUID) LEFT OUTER JOIN TOPIC t4 ON (t4.CONFERENCE_UUID = t1.UUID) WHERE ((t1.UUID = 'ba604a3c-e95a-4569-84a9-7d4dedd08310') OR (t1.SHORT = 'ba604a3c-e95a-4569-84a9-7d4dedd08310'))

150120 14:00:45	   55 Query	SELECT DISTINCT t1.UUID, t1.ACKNOWLEDGEMENTS, t1.CONFLICTOFINTEREST, t1.DOI, t1.ISTALK, t1.MTIME, t1.REASONFORTALK, t1.SORTID, t1.STATE, t1.TEXT, t1.TITLE, t1.TOPIC, t1.CONFERENCE_UUID, t0.UUID, t0.CITE, t0.DEADLINE, t0.DESCRIPTION, t0.ENDDATE, t0.ISOPEN, t0.ISPUBLISHED, t0.LINK, t0.LOGO, t0.NAME, t0.SHORT, t0.STARTDATE, t0.THUMBNAIL FROM ABSTRACT t1 LEFT OUTER JOIN CONFERENCE t0 ON (t0.UUID = t1.CONFERENCE_UUID) WHERE ((t0.UUID = 'ba604a3c-e95a-4569-84a9-7d4dedd08310') AND (t1.STATE = 'Accepted')) ORDER BY t1.SORTID, t1.TITLE

**Comment by asobolev** [comment]
The actual timing for any of the requests is about 5-10 ms, so the database is not an issue
