### ISSUE TITLE
Migration to the new DB scheme

### ISSUE THREAD

**Issue by asobolev** [G-Node/GCA-Web#275]

**Comment by asobolev** [comment]
dump database:

pg_dump <databasename> > <outfile>

restore database:

psql -h localhost -d <dbname> -U <user> -W -f <filepath>

**Comment by asobolev** [comment]
-- delete "name" from affiliation

ALTER TABLE affiliation DROP COLUMN "name";

-- split account data

CREATE TABLE credentialslogin
(
  uuid VARCHAR(255) PRIMARY KEY NOT NULL,
  date BYTEA,
  hasher VARCHAR(255),
  isactive BOOL,
  password VARCHAR(255),
  salt VARCHAR(255),
  token VARCHAR(255),
  account_uuid VARCHAR(255),
  FOREIGN KEY (account_uuid) REFERENCES account (uuid)
);

INSERT INTO credentialslogin (uuid, hasher, isactive, password, salt, account_uuid) (
  SELECT uuid_in(md5(random()::text)::cstring), hasher, TRUE, password, salt, uuid
  FROM account
);

ALTER TABLE account
DROP COLUMN authenticationmethod,
DROP COLUMN provider,
DROP COLUMN userid,
DROP COLUMN secret,
DROP COLUMN token,
DROP COLUMN accesstoken,
DROP COLUMN expiresin,
DROP COLUMN refreshtoken,
DROP COLUMN tokentype,
DROP COLUMN hasher,
DROP COLUMN password,
DROP COLUMN salt;

-- delete tokens

DROP TABLE IF EXISTS tokens;

**Comment by gicmo** [comment]
I took the liberty to format the previous comments because they weren't really readable otherwise.

**Comment by asobolev** [comment]
Oh yes thanks!
