### ISSUE TITLE
Conference.short is not unique

### ISSUE THREAD

**Issue by asobolev** [G-Node/GCA-Web#281]
leads to error on conference access

**Comment by mpsonntag** [comment]
Conference.short is actually already unique. If a short description is used that already exists, the message "Error while fetching data from server: Internal Server Error" is displayed, while the actual error message reads "... Unique index or primary key violation: CONSTRAINT_INDEX_4 ON PUBLIC.CONFERENCE(SHORT) VALUES ..."

**Comment by gicmo** [comment]
Heh, true, @asobolev fixed it himself with commit bd2c374. Our error message sucks though.
