### ISSUE TITLE
increase character limit for Conference Description to 512

### ISSUE THREAD

**Issue by twachtler** [G-Node/GCA-Web#293]
and improve error message when it is too long
(currently: "Error while fetching data from server: Internal Server Error")

**Comment by twachtler** [comment]
limit is still 255 and the error is

IO error: Internal Server Error
Execution exception[[RollbackException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException Internal Exception: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(255) Error Code: 0 Call: UPDATE CONFERENCE SET DESCRIPTION = ? WHERE (UUID = ?) bind => [2 parameters bound] Query: UpdateObjectQuery(models.Conference@73cd1375)]]

**Comment by stoewer** [comment]
As it turns out this is a migration issue in the production database and will be fixes in the next rollout:

The a similar problem occurs in 3 other places. Here is a script that fixes the schema:
```sql
UPDATE pg_attribute SET atttypmod = 512+4 
WHERE attrelid = 'conference'::regclass AND attname = 'description';

UPDATE pg_attribute SET atttypmod = 300+4 
WHERE attrelid = 'abstract'::regclass AND attname = 'acknowledgements';

UPDATE pg_attribute SET atttypmod = 300+4 
WHERE attrelid = 'figure'::regclass AND attname = 'caption';

UPDATE pg_attribute SET atttypmod = 300+4 
WHERE attrelid = 'reference'::regclass AND attname = 'text';
```

The script is bases on [this article](http://sniptools.com/databases/resize-a-column-in-a-postgresql-table-without-changing-data)

**Comment by mpsonntag** [comment]
Successfully tested conf desc > 255 on a local postgres instance for both conference creation and update.
