### ISSUE TITLE
Server error when accesing ../myabstracts#/ (see below)

### ISSUE THREAD

**Issue by cgars** [G-Node/GCA-Web#363]
When accessing https://abstracts.g-node.org/myabstracts#, without having any abstracts, I get the following ISE (not further specified). 

Error while lading data [error, Internal Server Error]!
- Report no abstracts available or smth?
- lading-> loading?

**Comment by gicmo** [comment]
The type is in https://github.com/G-Node/GCA-Web/blob/268243e763e0e4d2e4c700fc19a12baf1b80174c/app/assets/javascripts/userdash.js#L46

**Comment by twachtler** [comment]
Similar when trying to access (as admin) the abstracts of a conference that has no abstracts yet, e.g.
https://abstracts.g-node.org/dashboard/conference/3b00ef16-84f7-49bf-878e-5dcc27479dbb/abstracts
Then the error is

Error while fetching data from server
Internal Server Error
