### ISSUE TITLE
Required fields for conference creation

### ISSUE THREAD

**Issue by twachtler** [G-Node/GCA-Web#383]
Trying to create a conference without setting abstract length or figure number results in
IO error: Internal Server Error
Execution exception[[JsResultException: JsResultException(errors:List((/mFigs,List(ValidationError(error.expected.jsnumber,WrappedArray())))))]]

Creating a conference without short name results in Internal Server Error - 500 when accessing the main page (conferences list)

**Comment by mpsonntag** [comment]
Closed by #422
