### ISSUE TITLE
Site admin can't add owner to conference

### ISSUE THREAD

**Issue by twachtler** [G-Node/GCA-Web#384]
The site admin should be able to modify the owners of a conference even if he is not owner of the conference

**Comment by cgars** [comment]
This kind of boils down to the question whether an admin should be able to modify objects that he is not an owner of. Its in principle as simple as changing [this](https://github.com/G-Node/GCA-Web/blob/6d350e3222742c0dad7919ce4d28b5d57ce5d80c/app/models/Owned.scala#L25)

from `isOwner(account) ` to     `isOwner(account) || account.isAdmin`


whether that is

**Comment by fschrader1992** [comment]
At the moment accountChecked.isAdmin is added to the conferenceService update function, so it is possible for the site admin to change settings of the conference, including adding/removing owners.
