### ISSUE TITLE
Abstract viewer: show topic and type to conference owners and admins

### ISSUE THREAD

**Issue by twachtler** [G-Node/GCA-Web#387]
Topics and abstract types should be visible under the same conditions as the state log

**Comment by cgars** [comment]
would be easiest to just pout it into "statelog.scala.html". 
however, for the following reasons i am not sure that that its where its best located.  

-  it would duplicate both choices in the submission view (and would therefore need to be reactive)
- its imho not part of the state 

it could also be part of the admin conference dashboard, but this introduces a lot "if there" checking and such.
