### ISSUE TITLE
Abstracts changing state

### ISSUE THREAD

**Issue by JiriVanek** [G-Node/GCA-Web#448]
If changing state with note and try to save long note, change of state fails. DB fails saving long text.
![image](https://user-images.githubusercontent.com/6449276/51306777-72edea80-1a3e-11e9-9ad0-0c5dd2705887.png)
short notes works fine

**Comment by fschrader1992** [comment]
Could you specify the conditions under which the error occurs (which abstract states, the length of your note)?

**Comment by JiriVanek** [comment]
in conference administration "Conference abstracts"
![image](https://user-images.githubusercontent.com/6449276/51426885-f0595c80-1bf0-11e9-8d5d-b300d78e9efd.png)
Set state with note. I tried long note longer that 255 characters and that fails, not sure if 255 is limit

**Comment by mpsonntag** [comment]
This seems to behave differently on the test h2 and the postgres database. h2 accepts any length note text, postgres does not and results in the error reported above.
