### ISSUE TITLE
Conference dependent general notice

### ISSUE THREAD

**Issue by mpsonntag** [G-Node/GCA-Web#470]
Add a general notice string that is 
- conference specific.
- can be defined via the conference admin panel.
- if available will be displayed as a notice on all pages within the range of this conference.

**Comment by fschrader1992** [comment]
The conference model currently has 21 parameters, the maximum allowed number. Simply adding a new parameter "notice" doesn't work. Some parameters of smae type have to be put together in Lists first, before a general notie can be added.

**Comment by twachtler** [comment]
This limitation has prevented adding other features in the past as well. I think it would be worthwhile to work out a solution.
